Repository 42Sloth/chat-service, pull requests merged in 2021-09, with the labels that each got.

#5 Main Page 레이아웃 구성
  src/App.tsx
  src/Assets/.gitkeep
  src/Assets/Chatpong_logo_trans.png
  src/Assets/img-campaign.jpg
  src/Components/.gitkeep
  src/Components/Navbar/Navbar.tsx
  src/Components/Navbar/NavbarStyle.ts
  src/Components/Section/MainPage/Section.tsx
  src/Components/Section/MainPage/SectionStyle.ts
  src/Components/index.ts
  src/Pages/.gitkeep
  src/Pages/Home/Home.tsx
  src/Pages/index.ts
  src/Styles/GlobalStyle.ts
Labels: enhancement

#9 [#7] Style : SignIn page 초기 레이아웃 구성
  src/App.tsx
  src/Pages/SignIn/SignIn.tsx
  src/Pages/SignIn/SignInStyle.ts
  src/Pages/index.ts
  src/Styles/GlobalStyle.ts
Labels: style

#12 메인페이지 하단 브랜드로고 추가, Section 컴포넌트 추가 및 Footer 구현
  src/Assets/Brand_Logo/carvana.png
  src/Assets/Brand_Logo/devacurl.png
  src/Assets/Brand_Logo/fox.png
  src/Assets/Brand_Logo/index.ts
  src/Assets/Brand_Logo/intuit.png
  src/Assets/Brand_Logo/kiva.png
  src/Assets/Brand_Logo/lonelyplanet.png
  src/Assets/Brand_Logo/target-logo.png
  src/Components/Footer/Footer.tsx
  src/Components/Footer/FooterMenu.tsx
  src/Components/Footer/FooterMenuStyle.ts
  src/Components/Footer/FooterStyle.ts
  src/Components/Navbar/Navbar.tsx
  src/Components/Navbar/NavbarStyle.ts
  src/Components/Section/MainPage/BrandLogo.tsx
  src/Components/Section/MainPage/BrandLogoStyle.ts
  src/Components/Section/MainPage/Section.tsx
  src/Components/Section/MainPage/SectionStyle.ts
  src/Components/Section/MainPage/WelcomeFooter.tsx
  src/Components/Section/MainPage/WelcomeFooterStyle.ts
  src/Components/index.ts
  src/Pages/Home/Home.tsx
  src/Pages/SignIn/SignIn.tsx
  src/Styles/GlobalStyle.ts
Labels: feat

#11 [#6] feat: 로그인 후 메인 페이지 구성
  src/Components/Section/AnotherPage/AnotherPage.tsx
  src/Components/Section/AnotherPage/AnotherPageStyle.ts
  src/Components/Section/AnotherPage/WorkSpaceList/WorkSpaceList.tsx
  src/Components/Section/AnotherPage/WorkSpaceList/WorkSpaceListStyle.ts
  src/Components/index.ts
  src/Pages/Home/Home.tsx
  src/Styles/Colors.ts
  src/Styles/index.ts
  src/Types/IWorkSpaceItem.ts
  src/Types/IWorkSpaceList.ts
  src/Types/index.ts
Labels: feat

#13 [#10] 회원 가입 페이지 초기 레이아웃 구성
  src/App.tsx
  src/Components/Navbar/Navbar.tsx
  src/Pages/SignIn/SignIn.tsx
  src/Pages/SignIn/SignInStyle.ts
  src/Pages/SignUp/SignUp.tsx
  src/Pages/SignUp/SignUpStyle.ts
  src/Pages/index.ts
Labels: style

#17 #16 Firebase 초기 세팅
  fBase.js
  package-lock.json
  package.json
  src/Assets/Chatpong_logo_trans_white.png
Labels: feat

#20 #18 로그인 기능 구현
  package-lock.json
  src/App.tsx
  src/Components/Section/AnotherPage/AnotherPage.tsx
  src/Pages/SignIn/SignIn.tsx
  src/Pages/SignInSuccess/SignInSuccess.tsx
  src/Pages/index.ts
  src/Types/ISignInForm.ts
  src/Types/index.ts
  src/fBase.js
Labels: feat

#22 로그인, 로그아웃 상태 관리
  src/Components/Footer/Footer.tsx
  src/Components/Footer/FooterMenu.tsx
  src/Components/FormButton/FormButton.tsx
  src/Components/FormButton/FormButtonStyle.ts
  src/Components/Navbar/Navbar.tsx
  src/Components/Navbar/NavbarStyle.ts
  src/Components/index.ts
  src/Pages/Home/Home.tsx
  src/Pages/SignIn/SignIn.tsx
  src/Pages/SignIn/SignInStyle.ts
  src/Pages/SignIn/SignInSuccess/SignInSuccess.tsx
  src/Pages/SignUp/SignUp.tsx
  src/Pages/index.ts
Labels: feat, refactor

#24 #23 로그인시 상태값 저장 및 인증지속성을 위한 오류 처리
  src/Components/Navbar/Navbar.tsx
  src/Pages/SignIn/SignIn.tsx
  src/Pages/SignIn/SignInSuccess/SignInSuccess.tsx
  src/Pages/SignUp/SignUp.tsx
  src/Pages/SignUp/SignUpStyle.ts
  src/Styles/FormStyle.ts
Labels: fix

#29 로그인 상태 유지, 전역 관리 및 observing
  src/App.tsx
  src/Components/Navbar/Navbar.tsx
  src/Components/Navbar/NavbarStyle.ts
  src/Pages/SignIn/SignIn.tsx
  src/Pages/SignUp/SignUp.tsx
  src/Pages/index.ts
  src/Recoil/.gitkeep
  src/Recoil/atom.ts
Labels: feat

#30 #14 Chat페이지 Header 레이아웃 구현
  src/Assets/profile_kbs.jpg
  src/Components/ChatPannel/HeaderPannel/HeaderPannel.tsx
  src/Components/ChatPannel/HeaderPannel/HeaderPannelStyle.ts
  src/Pages/Chat/ChatPage.tsx
Labels: style

#31 #14 DM, Room List UI 구현 및 MockData 생성
  package-lock.json
  package.json
  src/Assets/MOCK_DATA.js
  src/Components/ChatPannel/SidePannel/ChatRoom.tsx
  src/Components/ChatPannel/SidePannel/ChatRoomStyle.ts
  src/Components/ChatPannel/SidePannel/DirectMessage.tsx
  src/Components/ChatPannel/SidePannel/DirectMessageStyle.ts
  src/Components/ChatPannel/SidePannel/SidePannel.tsx
  src/Components/ChatPannel/SidePannel/SidePannelStyle.ts
  src/Pages/Chat/ChatPage.tsx
Labels: style

#32 Chat Main Pannel
  package-lock.json
  src/Components/ChatPannel/HeaderPannel/HeaderPannel.tsx
  src/Components/ChatPannel/MainPannel/MainPannel.tsx
  src/Components/ChatPannel/MainPannel/Message.tsx
  src/Components/ChatPannel/MainPannel/Message/Message.tsx
  src/Components/ChatPannel/MainPannel/Message/MessageStyle.ts
  src/Components/ChatPannel/MainPannel/MessageForm/MessageForm.tsx
  src/Components/ChatPannel/MainPannel/MessageForm/MessageFormStyle.ts
  src/Components/ChatPannel/MainPannel/MessageFrom.tsx
  src/Components/ChatPannel/MainPannel/MessageHeader.tsx
  src/Components/ChatPannel/MainPannel/MessageHeader/MessageHeader.tsx
  src/Components/ChatPannel/MainPannel/MessageHeader/MessageHeaderStyle.ts
  src/Components/ChatPannel/MainPannel/index.ts
  src/Components/index.ts
  src/Pages/Chat/ChatPage.tsx
Labels: style

#33 메세지 Component 구현
  src/Components/ChatPannel/MainPannel/MainPannel.tsx
  src/Components/ChatPannel/MainPannel/Message/Message.tsx
  src/Components/ChatPannel/MainPannel/Message/MessageStyle.ts
  src/Components/ChatPannel/MainPannel/MessageField/MessageField.tsx
  src/Components/ChatPannel/MainPannel/MessageField/MessageFieldStyle.ts
  src/Components/ChatPannel/MainPannel/index.ts
  src/Components/ChatPannel/SidePannel/SidePannelStyle.ts
  src/Components/Navbar/Navbar.tsx
Labels: style

#35 #14, #34 전체 Member 리스트 구현
  src/Assets/MOCK_DATA.js
  src/Components/ChatPannel/SidePannel/MemberList.tsx
  src/Components/ChatPannel/SidePannel/MemberListStyle.ts
  src/Pages/Chat/ChatPage.tsx
  src/fBase.js
Labels: feat, style
